-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 18:37:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`login_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login_info` (
  `ID` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `PASSWORD` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `PASSWORD_ERROR_COUNT` INT NULL DEFAULT 0,
  `PASSWORD_ERROR_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_info` (
  `ID` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `ENG_NAME` VARCHAR(45) NULL,
  `GENDER` NCHAR(1) NOT NULL,
  `BIRTH_DATE` NCHAR(8) NOT NULL,
  `REAL_NUMBER` VARCHAR(300) NOT NULL,
  `ZIP_CODE` INT(6) NOT NULL,
  `ADDRESS` VARCHAR(200) NOT NULL,
  `ADDRESS_DTL` VARCHAR(150) NULL,
  `EMAIL` VARCHAR(15) NOT NULL,
  `EMAIL_ADDRESS` VARCHAR(30) NOT NULL,
  `PHONE_NUMBER` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_user_info_login_info_idx` (`ID` ASC),
  CONSTRAINT `fk_user_info_login_info`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`login_info` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profrssor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `PROFESSOR_CODE` VARCHAR(10) NOT NULL,
  `ID` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `SALARY` INT NOT NULL,
  `ENT_DATE` NCHAR(8) NOT NULL COMMENT '입사일',
  `RET_DATE` NCHAR(8) NULL COMMENT '퇴사일',
  `USE_YN` NCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`PROFESSOR_CODE`),
  INDEX `fk_PROFESSOR_USER_INFO1_idx` (`ID` ASC),
  CONSTRAINT `fk_PROFESSOR_USER_INFO1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`USER_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `STUDENT_CODE` VARCHAR(10) NOT NULL,
  `ID` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `ENT_DATE` NCHAR(8) NOT NULL COMMENT '입학일',
  `RET_DATE` NCHAR(8) COMMENT '졸업일',
  `GRADE` NCHAR(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`STUDENT_CODE`),
  INDEX `fk_STUDENT_USER_INFO1_idx` (`ID` ASC),
  CONSTRAINT `fk_STUDENT_USER_INFO1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`USER_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`major` ;

CREATE TABLE IF NOT EXISTS `mydb`.`major` (
  `MAJOR_CODE` NCHAR(2) NOT NULL COMMENT '학과_코드',
  `PROFESSOR_HEAD_USER_CODE` VARCHAR(10) NOT NULL COMMENT '학과_지도교수',
  `MAJOR_NAME` VARCHAR(45) NOT NULL COMMENT '학과_명',
  `MAJOR_PHONE_NUMBER` VARCHAR(20) NOT NULL COMMENT '학과_연락처',
  `USE_YN` NVARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부_YN',
  PRIMARY KEY (`MAJOR_CODE`),
  INDEX `fk_MAJOR_PROFESSOR1_idx` (`PROFESSOR_HEAD_USER_CODE` ASC),
  CONSTRAINT `fk_MAJOR_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_HEAD_USER_CODE`)
    REFERENCES `mydb`.`PROFESSOR` (`PROFESSOR_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`minor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`minor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`minor` (
  `MINOR_CODE` NCHAR(4) NOT NULL COMMENT '과목_코드',
  `MAJOR_CODE` NCHAR(2) NOT NULL COMMENT '학과_코드',
  `PROFESSOR_USER_CODE` VARCHAR(10) NOT NULL COMMENT '과목_지도교수',
  `MINOR_NAME` VARCHAR(45) NOT NULL COMMENT '과목_명',
  `MINOR_SCORE` INT NOT NULL COMMENT '과목_학점',
  `USE_YN` NVARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부_YN',
  INDEX `fk_MINOR_MAJOR1_idx` (`MAJOR_CODE` ASC),
  PRIMARY KEY (`MINOR_CODE`),
  INDEX `fk_MINOR_PROFESSOR1_idx` (`PROFESSOR_USER_CODE` ASC),
  CONSTRAINT `fk_MINOR_MAJOR1`
    FOREIGN KEY (`MAJOR_CODE`)
    REFERENCES `mydb`.`MAJOR` (`MAJOR_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MINOR_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_USER_CODE`)
    REFERENCES `mydb`.`PROFESSOR` (`PROFESSOR_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_grade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_grade` (
  `GRADE` NCHAR(1) NOT NULL,
  `STUDENT_CODE` VARCHAR(10) NOT NULL,
  `MAJOR_CODE` NCHAR(2) NOT NULL,
  INDEX `fk_STUDENT_MAJOR_MAJOR1_idx` (`MAJOR_CODE` ASC),
  INDEX `fk_STUDENT_MAJOR_STUDENT1_idx` (`STUDENT_CODE` ASC),
  PRIMARY KEY (`GRADE`, `STUDENT_CODE`),
  CONSTRAINT `fk_STUDENT_MAJOR_MAJOR1`
    FOREIGN KEY (`MAJOR_CODE`)
    REFERENCES `mydb`.`MAJOR` (`MAJOR_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_MAJOR_STUDENT1`
    FOREIGN KEY (`STUDENT_CODE`)
    REFERENCES `mydb`.`STUDENT` (`STUDENT_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`student_semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_semester` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_semester` (
  `SEMESTER` NCHAR(1) NOT NULL,
  `GRADE` NCHAR(1) NOT NULL,
  `STUDENT_CODE` VARCHAR(10) NOT NULL,
  `MINOR_CODE` NCHAR(4) NOT NULL,
  `MID_SCORE` INT(3),
  `FINAL_SCORE` INT(3),
  PRIMARY KEY (`SEMESTER`, `GRADE`, `STUDENT_CODE`, `MINOR_CODE`),
  INDEX `fk_STUDENT_SEMESTER_MINOR1_idx` (`MINOR_CODE` ASC),
  CONSTRAINT `fk_STUDENT_SEMESTER_STUDENT_GRADE1`
    FOREIGN KEY (`GRADE` , `STUDENT_CODE`)
    REFERENCES `mydb`.`STUDENT_GRADE` (`GRADE` , `STUDENT_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_SEMESTER_MINOR1`
    FOREIGN KEY (`MINOR_CODE`)
    REFERENCES `mydb`.`MINOR` (`MINOR_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
